#Problem J1: 0123456789 - 2002 (SirNooby)
number = int(input())

if number == 0:
    print(" * * *")
    print("*     *")
    print("*     *")
    print("*     *")
    print("")
    print("*     *")
    print("*     *")
    print("*     *")
    print(" * * *")

if number == 1:
    print("")
    print("      *")
    print("      *")
    print("      *")
    print("")
    print("      *")
    print("      *")
    print("      *")
    print("")

if number == 2:
    print(" * * *")
    print("      *")
    print("      *")
    print("      *")
    print(" * * *")
    print("*")
    print("*")
    print("*")
    print(" * * *")

if number == 3:
    print(" * * *")
    print("      *")
    print("      *")
    print("      *")
    print(" * * *")
    print("      *")
    print("      *")
    print("      *")
    print(" * * *")

if number == 4:
    print("")
    print("*     *")
    print("*     *")
    print("*     *")
    print(" * * *")
    print("      *")
    print("      *")
    print("      *")
    print("")

if number == 5:
    print(" * * *")
    print("*")
    print("*")
    print("*")
    print(" * * *")
    print("      *")
    print("      *")
    print("      *")
    print(" * * *")

if number == 6:
    print(" * * *")
    print("*")
    print("*")
    print("*")
    print(" * * *")
    print("*     *")
    print("*     *")
    print("*     *")
    print(" * * *")

if number == 7:
    print(" * * *")
    print("      *")
    print("      *")
    print("      *")
    print("")
    print("      *")
    print("      *")
    print("      *")
    print("")

if number == 8:
    print(" * * *")
    print("*     *")
    print("*     *")
    print("*     *")
    print(" * * *")
    print("*     *")
    print("*     *")
    print("*     *")
    print(" * * *")

if number == 9:
    print(" * * *")
    print("*     *")
    print("*     *")
    print("*     *")
    print(" * * *")
    print("      *")
    print("      *")
    print("      *")
    print(" * * *")

